const attentionEvents = [
  {
    id: "evt-001",
    topic: "Cost of living",
    entity: "Candidate A",
    state: "Lagos",
    zone: "South West",
    platform: "X",
    sourceType: "social",
    language: "English",
    sentiment: "negative",
    emotion: "frustration",
    stance: "questioning",
    trust: "skeptical",
    narrative: "Hardship and food prices",
    intensity: 86,
    urgency: 88,
    attention: 128400,
    velocity: 34,
    confidence: 0.91,
    influence: 78,
    text: "Food prices and transport costs are dominating the conversation after morning commute clips went viral.",
    evidenceUrl: "https://example.com/social/cost-living-lagos",
    timestamp: "2026-05-06T07:45:00+01:00",
  },
  {
    id: "evt-002",
    topic: "Jobs and youth",
    entity: "Candidate A",
    state: "Abuja",
    zone: "North Central",
    platform: "TikTok",
    sourceType: "video",
    language: "Pidgin",
    sentiment: "positive",
    emotion: "hope",
    stance: "supporting",
    trust: "open",
    narrative: "Youth opportunity",
    intensity: 72,
    urgency: 54,
    attention: 93400,
    velocity: 41,
    confidence: 0.84,
    influence: 66,
    text: "Short videos about practical job programs are gaining traction with youth creators.",
    evidenceUrl: "https://example.com/video/jobs-youth-abuja",
    timestamp: "2026-05-06T08:10:00+01:00",
  },
  {
    id: "evt-003",
    topic: "Security",
    entity: "Opponent B",
    state: "Kaduna",
    zone: "North West",
    platform: "News",
    sourceType: "web",
    language: "English",
    sentiment: "negative",
    emotion: "fear",
    stance: "demanding action",
    trust: "low trust",
    narrative: "Safety and state capacity",
    intensity: 93,
    urgency: 96,
    attention: 147200,
    velocity: 49,
    confidence: 0.89,
    influence: 82,
    text: "Local news coverage and reposts are pushing security concerns to the top of the regional conversation.",
    evidenceUrl: "https://example.com/news/security-kaduna",
    timestamp: "2026-05-06T08:20:00+01:00",
  },
  {
    id: "evt-004",
    topic: "Education",
    entity: "Candidate A",
    state: "Oyo",
    zone: "South West",
    platform: "Facebook",
    sourceType: "social",
    language: "Yoruba",
    sentiment: "mixed",
    emotion: "concern",
    stance: "requesting clarity",
    trust: "uncertain",
    narrative: "Schools and teacher quality",
    intensity: 58,
    urgency: 47,
    attention: 48200,
    velocity: 18,
    confidence: 0.79,
    influence: 42,
    text: "Parents and teachers are asking for clearer education commitments after a town hall clip.",
    evidenceUrl: "https://example.com/social/education-oyo",
    timestamp: "2026-05-06T08:32:00+01:00",
  },
  {
    id: "evt-005",
    topic: "Infrastructure",
    entity: "Candidate A",
    state: "Rivers",
    zone: "South South",
    platform: "YouTube",
    sourceType: "video",
    language: "English",
    sentiment: "positive",
    emotion: "pride",
    stance: "supporting",
    trust: "trusting",
    narrative: "Roads and visible delivery",
    intensity: 69,
    urgency: 43,
    attention: 77400,
    velocity: 25,
    confidence: 0.86,
    influence: 61,
    text: "Infrastructure explainer videos are being shared positively across local creator channels.",
    evidenceUrl: "https://example.com/video/infrastructure-rivers",
    timestamp: "2026-05-06T08:44:00+01:00",
  },
  {
    id: "evt-006",
    topic: "Corruption",
    entity: "Candidate A",
    state: "Kano",
    zone: "North West",
    platform: "Blogs",
    sourceType: "web",
    language: "Hausa",
    sentiment: "negative",
    emotion: "distrust",
    stance: "opposing",
    trust: "low trust",
    narrative: "Credibility and elite capture",
    intensity: 81,
    urgency: 74,
    attention: 68800,
    velocity: 39,
    confidence: 0.82,
    influence: 58,
    text: "Blog commentary around corruption allegations is spreading into repost networks.",
    evidenceUrl: "https://example.com/blog/corruption-kano",
    timestamp: "2026-05-06T09:02:00+01:00",
  },
  {
    id: "evt-007",
    topic: "Healthcare",
    entity: "Candidate A",
    state: "Enugu",
    zone: "South East",
    platform: "Instagram",
    sourceType: "social",
    language: "Igbo",
    sentiment: "mixed",
    emotion: "hope",
    stance: "requesting clarity",
    trust: "open",
    narrative: "Primary care access",
    intensity: 52,
    urgency: 38,
    attention: 39200,
    velocity: 14,
    confidence: 0.76,
    influence: 35,
    text: "Healthcare access is generating moderate interest around clinic upgrades and maternal care.",
    evidenceUrl: "https://example.com/social/health-enugu",
    timestamp: "2026-05-06T09:18:00+01:00",
  },
  {
    id: "evt-008",
    topic: "Fuel prices",
    entity: "Candidate A",
    state: "Edo",
    zone: "South South",
    platform: "X",
    sourceType: "social",
    language: "Pidgin",
    sentiment: "negative",
    emotion: "anger",
    stance: "demanding action",
    trust: "skeptical",
    narrative: "Transport hardship",
    intensity: 91,
    urgency: 92,
    attention: 112600,
    velocity: 46,
    confidence: 0.9,
    influence: 74,
    text: "Transport price complaints are accelerating and linking back to fuel policy credibility.",
    evidenceUrl: "https://example.com/social/fuel-edo",
    timestamp: "2026-05-06T09:26:00+01:00",
  },
  {
    id: "evt-009",
    topic: "Women entrepreneurship",
    entity: "Candidate A",
    state: "Kwara",
    zone: "North Central",
    platform: "Web",
    sourceType: "web",
    language: "English",
    sentiment: "positive",
    emotion: "hope",
    stance: "supporting",
    trust: "open",
    narrative: "Access to capital",
    intensity: 64,
    urgency: 35,
    attention: 35600,
    velocity: 22,
    confidence: 0.8,
    influence: 38,
    text: "Local coverage of women business grants is producing a constructive policy conversation.",
    evidenceUrl: "https://example.com/news/women-kwara",
    timestamp: "2026-05-06T09:39:00+01:00",
  },
  {
    id: "evt-010",
    topic: "Power supply",
    entity: "Opponent B",
    state: "Abia",
    zone: "South East",
    platform: "YouTube",
    sourceType: "video",
    language: "English",
    sentiment: "negative",
    emotion: "frustration",
    stance: "mocking",
    trust: "low trust",
    narrative: "Failed promises",
    intensity: 77,
    urgency: 63,
    attention: 64100,
    velocity: 31,
    confidence: 0.83,
    influence: 57,
    text: "Commentary videos are mocking old power promises and comparing candidates' records.",
    evidenceUrl: "https://example.com/video/power-abia",
    timestamp: "2026-05-06T09:50:00+01:00",
  },
  {
    id: "evt-011",
    topic: "Agriculture",
    entity: "Candidate A",
    state: "Benue",
    zone: "North Central",
    platform: "News",
    sourceType: "web",
    language: "English",
    sentiment: "mixed",
    emotion: "concern",
    stance: "questioning",
    trust: "uncertain",
    narrative: "Food security and farmers",
    intensity: 67,
    urgency: 71,
    attention: 52400,
    velocity: 28,
    confidence: 0.81,
    influence: 52,
    text: "Farmers' groups are asking for more detail on security, storage, and market access.",
    evidenceUrl: "https://example.com/news/agriculture-benue",
    timestamp: "2026-05-06T10:01:00+01:00",
  },
  {
    id: "evt-012",
    topic: "Candidate trust",
    entity: "Candidate A",
    state: "Lagos",
    zone: "South West",
    platform: "X",
    sourceType: "social",
    language: "English",
    sentiment: "mixed",
    emotion: "skepticism",
    stance: "questioning",
    trust: "skeptical",
    narrative: "Competence versus credibility",
    intensity: 73,
    urgency: 69,
    attention: 89800,
    velocity: 37,
    confidence: 0.87,
    influence: 71,
    text: "Candidate trust is drawing mixed attention as users compare competence claims with old statements.",
    evidenceUrl: "https://example.com/social/trust-lagos",
    timestamp: "2026-05-06T10:14:00+01:00",
  },
  {
    id: "evt-013",
    topic: "Food shortage",
    entity: "Opponent B",
    state: "Oyo",
    zone: "South West",
    platform: "Facebook",
    sourceType: "social",
    language: "English",
    sentiment: "negative",
    emotion: "anger",
    stance: "demanding action",
    trust: "low trust",
    narrative: "Teachers, school meals, and family hardship",
    intensity: 88,
    urgency: 91,
    attention: 103500,
    velocity: 44,
    confidence: 0.88,
    influence: 69,
    text: "Teachers are angry about food shortages affecting school attendance and classroom concentration.",
    evidenceUrl: "https://example.com/social/teachers-food-shortage-oyo",
    timestamp: "2026-05-06T10:27:00+01:00",
  },
  {
    id: "evt-014",
    topic: "Food shortage",
    entity: "Candidate A",
    state: "Oyo",
    zone: "South West",
    platform: "News",
    sourceType: "web",
    language: "Yoruba",
    sentiment: "negative",
    emotion: "frustration",
    stance: "requesting clarity",
    trust: "skeptical",
    narrative: "Teacher welfare and food security",
    intensity: 79,
    urgency: 83,
    attention: 74400,
    velocity: 33,
    confidence: 0.83,
    influence: 54,
    text: "Local reporting says teacher groups want a practical food-security and school-support response, not slogans.",
    evidenceUrl: "https://example.com/news/teachers-food-security-oyo",
    timestamp: "2026-05-06T10:34:00+01:00",
  },
];

const recommendations = [
  {
    id: "rec-001",
    status: "red",
    title: "Pause celebratory content in Kaduna and Edo",
    rationale: "Security and fuel-price anger are both high intensity with fast velocity.",
    action: "Lead with empathy, acknowledge hardship, and route a fact-backed response through legal/comms review.",
    owner: "War Room Lead",
  },
  {
    id: "rec-002",
    status: "green",
    title: "Push youth jobs explainer in Abuja",
    rationale: "Jobs and youth attention is rising with hopeful sentiment and creator amplification.",
    action: "Publish a practical jobs thread/video and brief youth surrogates with verified talking points.",
    owner: "Digital Director",
  },
  {
    id: "rec-003",
    status: "amber",
    title: "Clarify education policy in Oyo",
    rationale: "Parent and teacher conversation is mixed but open to detail.",
    action: "Release a short FAQ and prepare local radio notes in English and Yoruba.",
    owner: "Policy Team",
  },
  {
    id: "rec-004",
    status: "red",
    title: "Investigate corruption narrative in Kano blogs",
    rationale: "Low-trust commentary is spreading from web sources into social reposts.",
    action: "Assemble evidence pack, verify claims, and decide whether to respond or ignore.",
    owner: "Comms + Legal",
  },
];

const oppositionProfiles = [
  {
    id: "oppo-001",
    name: "Opponent B",
    party: "Opposition Coalition",
    watchlist: ["education", "food prices", "school feeding", "teacher welfare", "security"],
    publicClaims: [
      {
        id: "claim-001",
        topic: "Food shortage",
        claim: "Opponent B's public education plan has not published a costed school-feeding or teacher-support implementation schedule.",
        status: "needs verification",
        evidenceUrl: "https://example.com/opposition/education-plan-review",
      },
      {
        id: "claim-002",
        topic: "Food shortage",
        claim: "Local commentators are connecting current food-shortage anger to opposition-led criticism without a concrete relief proposal.",
        status: "monitoring",
        evidenceUrl: "https://example.com/opposition/food-shortage-commentary",
      },
    ],
  },
  {
    id: "oppo-002",
    name: "Opponent C",
    party: "Reform Front",
    watchlist: ["jobs", "power supply", "corruption", "candidate trust"],
    publicClaims: [
      {
        id: "claim-003",
        topic: "Power supply",
        claim: "Opponent C is being compared against prior power-sector statements in creator commentary.",
        status: "monitoring",
        evidenceUrl: "https://example.com/opposition/power-claims",
      },
    ],
  },
];

module.exports = { attentionEvents, recommendations, oppositionProfiles };
